# Generated by Django 3.2.8 on 2021-10-28 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(default=None, null=True)),
                ('state', models.CharField(choices=[('RUN', 'Running'), ('DONE', 'Done'), ('INTER', 'Interrupted')], default=('RUN', 'Running'), max_length=5)),
                ('state_order', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
